### TensorFlow Object Detection API on Custom Dataset ### 
## By Jonathan L. Moran (jonathan.moran107@gmail.com) ###

### Default configurations to use
defaults:
    - dataset: waymo_open_dataset
    - model: ssd_resnet50
    - hyperparameters: hyperparameters1
    - hydra/run: run_config1
    - override hydra/help: help



