### TensorFlow Object Detection API on Custom Dataset ### 
## By Jonathan L. Moran (jonathan.moran107@gmail.com) ###


# Training/evaluation
# --------------------
# For local training/evaluation run with none/any/all of the following parameters:
# ```
# DIR_BASE:                               Path to the current `model` subdirectory.
# PIPELINE_CONFIG_PATH:                   Path to `pipeline.config` file.
# MODEL_OUT:                              Path to `/tmp/model_outputs/` folder.
# CHECKPOINT_DIR:                         Path to the pretrained weights/variables saved in `checkpoint` folder.
# NUM_TRAIN_STEPS:                        Number of training steps.
# EVAL_ON_TRAIN_DATA:                     If True, will evaluate on training data (only supported in distributed training).
# SAMPLE_1_OF_N_EVAL_EXAMPLES:            Number of evaluation samples to skip / will sample 1 of every n samples.
# SAMPLE_1_OF_N_EVAL_ON_TRAIN_EXAMPLES:   Number of training samples to skip for evaluation / only used if `eval_training_data` is True.
# EVAL_TIMEOUT:                           Number of seconds to wait for an evaluation checkpoint before exiting.
# USE_TPU:                                Whether the job is executing on a TPU.
# TPU_NAME:                               Name of the Cloud TPU for Cluster Resolvers.
# CHECKPOINT_EVERY_N:                     Integer defining how often to checkpoint.
# RECORD_SUMMARIES:                       Whether or not to record summaries defined by the model or training pipelines.
# NUM_WORKERS:                            When `num_workers` > 1, training uses 'MultiWorkerMirroredStrategy',
#                                         When `num_workers` = 1, training uses 'MirroredStrategy'.
#
# Overriding parameters is accomplished at runtime using the Basic Override syntax provided by Hydra:
#
# ```python
#
# python3 model_main_tf2.py \
#     model.dir_base={DIR_BASE} \
#     model.model_out={MODEL_OUT} \
#     model.pipeline_config_path={PIPELINE_CONFIG_PATH} \
#     model.model_out={MODEL_OUT} model.num_train_steps={NUM_TRAIN_STEPS} \
#     model.sample_1_of_n_eval_examples={SAMPLE_1_OF_N_EVAL_EXAMPLES} \
#     --...
# ```
# Note that braces "{}" should be used to perform interpolation on Python variables.
#
# See `configs/model/` for additional details on preconfigured values if running without parameters.


### List of all TensorFlow Object Detection API parameters
dir_base: ${hydra:runtime.cwd}                      # Path to the current `model` folder
model_out: ${.dir_base}/tmp/model_outputs           # Path to to `tmp/model_outputs` folder
checkpoint_dir: ${.dir_base}/checkpoint             # Path to the trained `checkpoint` folder
pipeline_config_path: ${.dir_base}/pipeline.config  # Path to pipeline configuration file
num_train_steps: 100                                # Number of training steps to perform
eval_on_train_data: False                           # Whether to evaluate on training data (only supported in distributed training)
sample_1_of_n_eval_examples: 1                      # Number of evaluation examples to skip / will sample 1 of every n samples
sample_1_of_n_eval_on_train_examples: None
eval_timeout: 25                                    # Number of seconds to wait for an evaluation checkpoint before exiting
use_tpu: False                                      # Whether the job is executing on a TPU
tpu_name: None                                      # Name of the Cloud TPU for Cluster Resolvers
checkpoint_every_n: 100                             # Integer defining how often to checkpoint
record_summaries: True                              # Whether or not to record summaries defined by the model or training pipelines.
num_workers: 1                                      # If 1, uses 'MirroredStrategy', if > 1, uses 'MultiWorkerMirroredStrategy'
